apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
patches:
- target:
    kind: Deployment 
  patch: |-
    - op: replace
      path: /spec/template/spec/containers/0/resources
      value: 
        limits:
          memory: "128Mi"
          cpu: "250m"
